title: "Zerina Aličehajić"
subtitle: "Economics, Policy & Geopolitics"
url: "https://zerina-alicehajic.github.io"
baseurl: "/portfolio_research"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

# Site Author / Sidebar Profile
author:
  name: "Zerina Aličehajić"
  avatar: "/assets/images/profilepic.jpg"
  bio: "bacc. Management (MIT) | Graduate student- Department of Economics"
  location: "Sarajevo, BiH"
  employer: "EFSA"
  linkedin: "https://linkedin.com/in/zerina-alicehajic"
  github: "zerina-alicehajic"

      
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
  # Root files (like index.md or about.md)
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true

